### ISSUE TITLE
Git package declaration throws duplicate declaration error 

### ISSUE THREAD

**Issue by Jmeyering** [scotty-c/puppet-golang#1]
When using another module to install git, we have a duplicate declaration error displayed

```
Error: Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: Package[git] is already declared in file /etc/puppet/modules/.../manifests/profiles/ubuntu_webserver.pp:28; cannot redeclare at /etc/puppet/modules/golang/manifests/init.pp:12 at /etc/puppet/modules/golang/manifests/init.pp:12:3 on node ...
```

**Comment by scotty-c** [comment]
This module depends on to manage git ````puppetlabs/vcsrepo```` If you are using another module to control git you might need to fork and refactor. I always use this module to control source control repos

**Comment by scotty-c** [comment]
Thanks for the feedback, the module needs git installed to work. If you are declaring the package elsewhere maybe fork the module and remove the package.

**Comment by Jmeyering** [comment]
:) That's what I ended up doing. Any thought to possible using the
puppet/vscrepo module to handle the git stuff?

**Comment by scotty-c** [comment]
Good idea, I have removed the git package. Now vcsrepo is looking after everything
