### ISSUE TITLE
Error 400 on SERVER: Found 2 errors

### ISSUE THREAD

**Issue by jordigg** [scotty-c/puppet-golang#2]
I'm getting the following error "Error 400 on SERVER: Found 2 errors" when I try to use the example on the docs, I'm using Puppet v4.

class { 'golang':
    base_dir         => '/usr/local/go',
    from_source   => true,
    version            => 'go1.4.1',
    goroot             => "$GOPATH/bin:/usr/local/go/bin:$PATH",
    workdir            => '/usr/local/',
}

Seems related to the $GOPATH and $PATH variables. What am I doing wrong?

Thank you!

**Comment by scotty-c** [comment]
Hey @jordigg would you be able to paste the full error message for me please

**Comment by jordigg** [comment]
Here the log from the PuppetMaster:

2016-01-26 16:39:50,337 ERROR [qtp1617241010-67] [puppet-server] Puppet Illegal variable name, The given name 'GOPATH' does not conform to the naming rule /^((::)?[a-z]\w_)_((::)?[a-z_]\w_)$/
2016-01-26 16:39:50,338 ERROR [qtp1617241010-67] [puppet-server] Puppet Illegal variable name, The given name 'PATH' does not conform to the naming rule /^((::)?[a-z]\w_)_((::)?[a-z_]\w_)$/

**Comment by scotty-c** [comment]
Sorry there is a typo in the readme, if you change goroot => "$GOPATH/bin:/usr/local/go/bin:$PATH",
to goroot => '$GOPATH/bin:/usr/local/go/bin:$PATH', that should fix the issue.

**Comment by jordigg** [comment]
Now I'm getting:

Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Class[Golang]: has no parameter named 'version'

Should it be like the second example using: `package_version => "go1.5.3"` ?

Thanks for your help, using the module with just include works, just having problems when trying to build from source. I want to install v1.5.3.

**Comment by jordigg** [comment]
Saw now on the code that you are using `source_version`. Will try with that.

**Comment by jordigg** [comment]
That fixed the error and then got

```
Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Invalid resource type vcsrepo at /etc/puppetlabs/code/environments/production/modules/golang/manifests/install.pp:8:5
```

Because the `puppetlabs/vcsrepo`module is required. Maybe it should be defined as requirement on the `metadata.json`file.

**Comment by scotty-c** [comment]
good morning @jordigg 

```
 "dependencies": [
    {"name":"puppetlabs/vcsrepo","version_requirement":">= 1.2.0"},
    {"name":"puppetlabs/stdlib","version_requirement":">= 4.1.0"}
  ]
}
```

It is in the metadata.json, I will push up the changes to the readme now

**Comment by jordigg** [comment]
Yes, saw it just after writing the comment. I'm just getting into Puppet so I though the modules required their dependencies and puppet itself or R10K on my specific case would deal with the missing ones automatically but that's not the case!

Thanks for your help @scotty-c and thanks for this useful module!

**Comment by scotty-c** [comment]
@jordigg Thanks for feedback and using the module

**Comment by jordigg** [comment]
Just FYI, the module doesn't compile versions >=go1.5.x but does for <=go1.4.x. Check https://golang.org/doc/install/source it's not compiled on C anymore and requires an extra step to compile using go1.4 or using gccgo-5 which is not available on Ubuntu 14.04 LTS repository by default.

A part from that, when I tried with v.1.4.1, as recommended on the Readme, the $PATH wasn't set correctly and I couldn't use the go command so I think the build from source part of the module needs some work. I'll try to check it and contribute.

For now maybe is easier to just get it already compiled from https://golang.org/dl/

**Comment by scotty-c** [comment]
@jordigg I found the issue, the variable scopes need to be updated for Puppet 4. Give me a couple of days and I will have a fix for this.

**Comment by scotty-c** [comment]
@jordigg I just posted a new version of the module. Let me know if it fixes the issue.

**Comment by scotty-c** [comment]
I am going to close this issue now. @jordigg Please re-open it if you are having an issue
