### ISSUE TITLE
Use archive instead of wget?

### ISSUE THREAD

**Issue by jyaworski** [scotty-c/puppet-golang#4]
Would it be possible to use https://github.com/voxpupuli/puppet-archive instead of the wget module? It's much more widely used and will lead to one less dependency (generally) in deployments.

**Comment by scotty-c** [comment]
@jyaworski  The wget module https://forge.puppet.com/maestrodev/wget has almost 1 million dl's on Puppetforge and in a Puppet aprroved module. So I am going to continue to use the wget module. If you prefer to use the archive module feel free to fork and make the necessary changes

**Comment by jyaworski** [comment]
@scotty-c right. Apparently I vastly underestimated this module.

Closing because... well, yeah.
